# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    changelog = prompt(text: "Changelog: ")
    increment_build_number(xcodeproj: "OnFarma.xcodeproj")
    match(
      type: "appstore",
      git_url: "https://github.com/Bayway/Certificates.git"
    ) # more information: https://codesigning.guide  
    gym(scheme: "OnFarma") # Build your app - more options available
    pilot    
    #build_app(scheme: "OnFarma")
    #upload_to_testflight
  end
end
